-- GIVE ACCESS TO MY POWER BI ACCOUNT EMAIL

CREATE USER [YassineMahboub@YASSINEMAHBOUB.onmicrosoft.com] FROM EXTERNAL PROVIDER;
GRANT SELECT ON DATABASE::facebook_ads TO [YassineMahboub@YASSINEMAHBOUB.onmicrosoft.com];

